stages:
  - test

test-java-app:
  stage: test
  image: gradle:8.13-jdk17
  tags:
    - students-buildkit-medium
  script:
    - cd backend
    - make test
  artifacts:
    paths:
      - backend/build/test-results/
      - backend/build/reports/
    when: always
  cache:
    paths:
      - backend/.gradle/

test-go-app:
  stage: test
  image: gradle:8.13-jdk17
  tags:
    - students-buildkit-medium
  script:
    - cd auth-service
    - make test
  artifacts:
    paths:
      - backend/build/test-results/
      - backend/build/reports/
    when: always
  cache:
    paths:
      - backend/.gradle/
