stages:
  - test

test-java-app:
  stage: test
  image: gradle:8.13-jdk17
  tags:
    - students-buildkit-medium
  script:
    - apt-get update && apt-get install -y make
    - cd backend
    - make test
  artifacts:
    paths:
      - backend/build/test-results/
      - backend/build/reports/
    when: always
  cache:
    paths:
      - backend/.gradle/

test-go-app:
  stage: test
  image: debian:bullseye
  tags:
    - students-buildkit-medium
  script:
    - apt-get update && apt-get install -y make openjdk-17-jdk curl unzip docker
    - docker --version
    - cd auth-service
    - make 
  artifacts:
    paths:
      - backend/build/test-results/
      - backend/build/reports/
    when: always
  cache:
    paths:
      - backend/.gradle/
