services:
  testpostgres:
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: -p 5433
    ports:
      - "5433:5433"


