spring.sql.init.mode=always
spring.application.name=bookswap
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/bookswap}
spring.datasource.username=root
spring.datasource.password=toor
spring.datasource.driver-class-name=org.postgresql.Driver
