name: Go CI

on:
  push:
    paths:
      - "auth-service/**"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "auth-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/auth-service/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('auth-service/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
